### ISSUE TITLE
Problem + Solution / Exception in thread "main" java.awt.AWTError: Assistive Technology not found

### ISSUE THREAD

**Issue by MikeMitterer** [winder/Universal-G-Code-Sender#1267]
I had the following problem but found already a solution - I'm writing this issue report for others with the same problem.

OS: KDE Neon 5.16
JDK: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

Universal-G-Code-Sender: 2.0 - 14. Aug 2019

Exception:
```bash
./start.sh 
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2020)
        at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
        at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
        at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
        at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
        at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
        at javax.swing.UIManager.initialize(UIManager.java:1459)
        at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
        at javax.swing.UIManager.getInstalledLookAndFeels(UIManager.java:419)
        at com.willwinder.universalgcodesender.MainWindow.main(MainWindow.java:180)
```
**Solution**
```txt
Edit the accessibility.properties file for OpenJDK:
sudo vim /etc/java-8-openjdk/accessibility.properties
Comment out the following line:
assistive_technologies=org.GNOME.Accessibility.AtkWrapper
```

**Comment by breiler** [comment]
Thanks, I've added it to our troubleshooting guide:
https://github.com/winder/Universal-G-Code-Sender/wiki/Troubleshooting-Overview#error-message-assistive-technology-not-found
