### ISSUE TITLE
UnsatisfiedLinkError when running on OSX 10.7.5

### ISSUE THREAD

**Issue by jordan5k** [winder/Universal-G-Code-Sender#136]
I hope this is an appropriate venue to post this question! When I try to run the start.sh file from terminal, the applet never opens and I get this error:

java.lang.UnsatisfiedLinkError: /Library/Java/Extensions/librxtxSerial.jnilib: dlopen(/Library/Java/Extensions/librxtxSerial.jnilib, 1): no suitable image found.  Did find:
    /Library/Java/Extensions/librxtxSerial.jnilib: no matching architecture in universal wrapper thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /Library/Java/Extensions/librxtxSerial.jnilib: dlopen(/Library/Java/Extensions/librxtxSerial.jnilib, 1): no suitable image found.  Did find:
    /Library/Java/Extensions/librxtxSerial.jnilib: no matching architecture in universal wrapper
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1894)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
    at com.willwinder.universalgcodesender.CommUtils.getSerialPortList(CommUtils.java:44)
    at com.willwinder.universalgcodesender.MainWindow.loadPortSelector(MainWindow.java:1133)
    at com.willwinder.universalgcodesender.MainWindow.initProgram(MainWindow.java:973)
    at com.willwinder.universalgcodesender.MainWindow.<init>(MainWindow.java:39)
    at com.willwinder.universalgcodesender.MainWindow$26.run(MainWindow.java:967)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

I tried reinstalling the newest Java, and followed the shapeoko suggestions to make the /var/lock directory (it already existed) and run "sudo chmod 777 /var/lock". No luck... Any suggestions?
Many thanks.

**Comment by ameyabap** [comment]
Do you have libtray.jnilib which would in 10.9.5? I am getting exact same error for this file.

**Comment by winder** [comment]
What build are you using?

**Comment by FlorianMalapel** [comment]
I have the same problem with osx 10.10.3, does someone have a link to download the files ?

**Comment by Jan982** [comment]
I have same problem, did anyone solve it?

**Comment by winder** [comment]
Try the latest nightly build. I fixed an OSX issue like this recently. If you have issues still create a new ticket with the backtrack and I can take a look.

**Comment by ghtali** [comment]
winder, thanks man, you saved my day 👍

**Comment by ghtali** [comment]
I've made a tutorial on StackOverflow.com it might help you: 

[http://stackoverflow.com/questions/37261533/rxtx-java-eclipse-on-mac/43278620#43278620](url)
