### ISSUE TITLE
UGS 2.0.8 initialization with GRBL 1.1h fails at $$ command due to $20=1

### ISSUE THREAD

**Issue by bLouChip** [winder/Universal-G-Code-Sender#1669]
UGS 2.0.8 SNAPSHOT is failing to initialize with GRBL 1.1h upon connection action. I press the connection button, then as the console displays the results of the $$ command issued during connection, the results quit streaming on or about the $20=1 message.  At this point of failure, the UGS to GRBL polling as indicated by the rx/tx LED on Arduino board is reduced to 1 every  3 seconds,  rather than the normal 5/sec.  If I disable GRBL soft limits with $20=0 command, then re-connect, then UGS seems to operate normally.  I had been using UGS 2.0.7 SNAPSHOT successfully.  I have also renamed previous version .ugs and .ugsplatform folders to force a new/fresh configuration of 2.0.8, no help.   For what it's worth, I saw this same problem using 2.0.7 nightly build from March 2021, and thus reverted back to using the 2.0.7 snapshot. 

Also, I just tried the latest 2.0.8 nightly build from July 24 2021 and it works fine, does not exhibit this problem. I would prefer not to use this version though in my production runs. 

Windows 10 OS
I have a 3 axis CNC, XYZ. 

Things seem to go wrong according to the message.log file about here:
WARNING [com.willwinder.universalgcodesender.AbstractCommunicator]: Couldn't send event
java.lang.IllegalArgumentException: Tried to get a-axis which is not set
	at com.willwinder.universalgcodesender.model.PartialPosition.getA(PartialPosition.java:143)
	at com.willwinder.universalgcodesender.model.PartialPosition$Builder.copy(PartialPosition.java:333)
	at com.willwinder.ugs.nbm.visualizer.renderables.MachineBoundries.onUGSEvent(MachineBoundries.java:70)
	at com.willwinder.universalgcodesender.model.GUIBackend.lambda$sendUGSEvent$3(GUIBackend.java:899)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.willwinder.universalgcodesender.model.GUIBackend.sendUGSEvent(GUIBackend.java:899)
	at com.willwinder.universalgcodesender.model.GUIBackend.onUpdatedFirmwareSetting(GUIBackend.java:922)
	at com.willwinder.universalgcodesender.firmware.grbl.GrblFirmwareSettingsCommunicatorListener.lambda$rawResponseListener$1(GrblFirmwareSettingsCommunicatorListener.java:237)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
	at com.willwinder.universalgcodesender.firmware.grbl.GrblFirmwareSettingsCommunicatorListener.rawResponseListener(GrblFirmwareSettingsCommunicatorListener.java:237)
	at com.willwinder.universalgcodesender.firmware.grbl.GrblFirmwareSettings.rawResponseListener(GrblFirmwareSettings.java:417)
	at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListeners(AbstractCommunicator.java:172)
[catch] at com.willwinder.universalgcodesender.AbstractCommunicator.lambda$new$0(AbstractCommunicator.java:194)
	at java.base/java.lang.Thread.run(Unknown Source)

The full message.log file is attached. 
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/6987026/messages.log)

Please advise. Thanks.

**Comment by breiler** [comment]
@bLouChip, this problem has been fixed in the nightly builds of UGS.
