### ISSUE TITLE
UGS java error

### ISSUE THREAD

**Issue by oliskcz** [winder/Universal-G-Code-Sender#1759]
### **Hello there!**
I have another issue.
**ISSUE:** So when i open gcode the editing window for it doesn't open and it gives me one error here is is:
![image](https://user-images.githubusercontent.com/68785534/147578354-e01c7d9b-1c8f-405e-94cb-f4eccbda6d15.png)
And heres the gcode: [g-code.txt](https://github.com/winder/Universal-G-Code-Sender/files/7785177/g-code.txt)
Thanks.

(EDIT: It gave me this error when i removed this M6 section from the gcode:
 **M5
G00 Z15.0000
G00 X0.0000 Y0.0000
T1
M6    
(MSG, Change to Tool Dia = 0.1000)
M0
G00 Z15.0000**)

**Comment by breiler** [comment]
Opens fine for me, what version of UGS are you running?
Can you post your log file: https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by oliskcz** [comment]
Im using ugs 2.0.9.
I cant find the logfile.
When i start milling the motor is not turning when i deleted the M6 (my motor is not burned or anything.

And this: ![javaw_N4OQPsKTCo](https://user-images.githubusercontent.com/68785534/147584470-0983b7da-60ee-406d-946e9f008449f182.png)
![javaw_ptxeJgK4YQ](https://user-images.githubusercontent.com/68785534/147584487-a75a8e9c-f4dc-48ad-a147a7080d4ae1a2.png)
![javaw_Z1TIh5uYtG](https://user-images.githubusercontent.com/68785534/147584506-47f9a85d-98c8-4709-ae54fae9e674b585.png)

**Comment by oliskcz** [comment]
Can you help me?

**Comment by breiler** [comment]
The screen shots you posted about warnings in the editor is because the editor highlighter doesn't recognize commands with padded zeros (G0 -> G00). I have made a fix for it but it will take some time for me to getting it merged. But those are just warnings, so you can ignore those.

It is really difficult to help without the log file. You could press the button "Show Details" and paste that content here which might give a clue.

**Comment by chappy1978** [comment]
Im getting the same issue when I connect my GRBL for the first time. 
Im using UGS 2.0.9, MacOS, GRBL-MEGA

java.lang.NullPointerException
	at com.willwinder.universalgcodesender.model.GUIBackend.canSend(GUIBackend.java:662)
	at com.willwinder.ugs.nbp.core.actions.StartAction.isEnabled(StartAction.java:75)
	at com.willwinder.ugs.nbp.core.actions.StartAction.lambda$UGSEvent$0(StartAction.java:70)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/7845891/messages.log)

**Comment by chappy1978** [comment]
I when and used the nightly build and that has cleared the Exception.

**Comment by breiler** [comment]
@chappy1978 thanks for the log. The errors in your log file is a known issue and a fix is on its way. But that should not cause the errors described by @oliskcz:
> gcode the editing window for it doesn't open

> When i start milling the motor is not turning when i deleted the M6 (my motor is not burned or anything and it works on other g-codes other than from flatCAM.)

Do you have the same problems as @oliskcz with it not opening or sending the file?

**Comment by breiler** [comment]
@oliskcz, @chappy1978 I have made some updates that should resolve this issue. Could you try the nightly build and see if things are working better for you?

**Comment by breiler** [comment]
Closing as we did not get a response from users.
