### ISSUE TITLE
Serial communications error

### ISSUE THREAD

**Issue by josemariaaraujo** [winder/Universal-G-Code-Sender#176]
I've been having problems with UGS. There seems to be a communication problem, some g-codes are skiped and had to abort a couple of jobs after the piece was ruined.
I'm running in Windows7 64bit with Java 32bit Version 7 update 60.
It happens randomly, some times at the beginning, others after a 1000 lines are done.
I don't suspect hardware problems because "stream.py" included with grbl ran just fine a job of 55k lines.

The error I get in the console is:
("O recurso pedido esta a ser utilizado." means  "The requested resource is in use")
```
Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7
Error 0xaa at /home/bob/foo/rxtx-devel/build/../src/termios.c(1278): O recurso pedido esta a ser utilizado.

java.lang.Exception
        at com.willwinder.universalgcodesender.AbstractController.commandSent(AbstractController.java:628)
        at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:206)
        at com.willwinder.universalgcodesender.AbstractCommunicator.dispatchListenerEvents(AbstractCommunicator.java:189)
        at com.willwinder.universalgcodesender.GrblCommunicator.streamCommands(GrblCommunicator.java:153)
        at com.willwinder.universalgcodesender.GrblCommunicator.responseMessage(GrblCommunicator.java:200)
        at com.willwinder.universalgcodesender.SerialConnection.serialEvent(SerialConnection.java:173)
        at gnu.io.RXTXPort.sendEvent(RXTXPort.java:732)
        at gnu.io.RXTXPort.eventLoop(Native Method)
        at gnu.io.RXTXPort$MonitorThread.run(RXTXPort.java:1575)
java.lang.Exception
        at com.willwinder.universalgcodesender.AbstractController.commandSent(AbstractController.java:628)
        at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:206)
        at com.willwinder.universalgcodesender.AbstractCommunicator.dispatchListenerEvents(AbstractCommunicator.java:189)
        at com.willwinder.universalgcodesender.GrblCommunicator.streamCommands(GrblCommunicator.java:153)
        at com.willwinder.universalgcodesender.AbstractController.sendStringToComm(AbstractController.java:442)
        at com.willwinder.universalgcodesender.AbstractController.queueCommandForComm(AbstractController.java:431)
        at com.willwinder.universalgcodesender.AbstractController.beginStreaming(AbstractController.java:532)
        at com.willwinder.universalgcodesender.MainWindow.sendButtonActionPerformed(MainWindow.java:1359)
        at com.willwinder.universalgcodesender.MainWindow.access$200(MainWindow.java:67)
        at com.willwinder.universalgcodesender.MainWindow$3.actionPerformed(MainWindow.java:246)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "Thread-5" java.lang.NullPointerException
        at com.willwinder.universalgcodesender.MainWindow.setStatusColorForState(MainWindow.java:1606)
        at com.willwinder.universalgcodesender.MainWindow.statusStringListener(MainWindow.java:2088)
        at com.willwinder.universalgcodesender.AbstractController.dispatchStatusString(AbstractController.java:730)
        at com.willwinder.universalgcodesender.GrblController.handlePositionString(GrblController.java:409)
        at com.willwinder.universalgcodesender.GrblController.rawResponseHandler(GrblController.java:146)
        at com.willwinder.universalgcodesender.AbstractController.rawResponseListener(AbstractController.java:717)
        at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:215)
        at com.willwinder.universalgcodesender.AbstractCommunicator.dispatchListenerEvents(AbstractCommunicator.java:189)
        at com.willwinder.universalgcodesender.GrblCommunicator.responseMessage(GrblCommunicator.java:190)
        at com.willwinder.universalgcodesender.SerialConnection.serialEvent(SerialConnection.java:173)
        at gnu.io.RXTXPort.sendEvent(RXTXPort.java:732)
        at gnu.io.RXTXPort.eventLoop(Native Method)
        at gnu.io.RXTXPort$MonitorThread.run(RXTXPort.java:1575```

**Comment by gabebear** [comment]
I'm having a similar issue on OSX

java.lang.NullPointerException
	at com.willwinder.universalgcodesender.AbstractController.commandSent(AbstractController.java:627)
	at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:206)
	at com.willwinder.universalgcodesender.AbstractCommunicator.dispatchListenerEvents(AbstractCommunicator.java:189)
	at com.willwinder.universalgcodesender.GrblCommunicator.streamCommands(GrblCommunicator.java:153)
	at com.willwinder.universalgcodesender.AbstractController.sendStringToComm(AbstractController.java:447)
	at com.willwinder.universalgcodesender.AbstractController.queueCommandForComm(AbstractController.java:436)
	at com.willwinder.universalgcodesender.AbstractController.beginStreaming(AbstractController.java:537)
	at com.willwinder.universalgcodesender.MainWindow.sendButtonActionPerformed(MainWindow.java:1677)
	at com.willwinder.universalgcodesender.MainWindow.sendButtonActionPerformed(MainWindow.java:1688)
	at com.willwinder.universalgcodesender.MainWindow.access$200(MainWindow.java:73)
	at com.willwinder.universalgcodesender.MainWindow$3.actionPerformed(MainWindow.java:286)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at com.willwinder.universalgcodesender.AbstractController.commandSent(AbstractController.java:627)
	at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:206)
	at com.willwinder.universalgcodesender.AbstractCommunicator.dispatchListenerEvents(AbstractCommunicator.java:189)
	at com.willwinder.universalgcodesender.GrblCommunicator.streamCommands(GrblCommunicator.java:153)
	at com.willwinder.universalgcodesender.AbstractController.sendStringToComm(AbstractController.java:447)
	at com.willwinder.universalgcodesender.AbstractController.queueCommandForComm(AbstractController.java:436)
	at com.willwinder.universalgcodesender.AbstractController.beginStreaming(AbstractController.java:537)
	at com.willwinder.universalgcodesender.MainWindow.sendButtonActionPerformed(MainWindow.java:1677)
	at com.willwinder.universalgcodesender.MainWindow.sendButtonActionPerformed(MainWindow.java:1688)
	at com.willwinder.universalgcodesender.MainWindow.access$200(MainWindow.java:73)
	at com.willwinder.universalgcodesender.MainWindow$3.actionPerformed(MainWindow.java:286)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
