### ISSUE TITLE
Visualize not starting in version 1.0.7

### ISSUE THREAD

**Issue by sthenge** [winder/Universal-G-Code-Sender#187]
I'm new to this so I appologize if my request is out of order.

I am trying to use ugs on a pentium 4 processor using xp home.  The main screen opens fine, but the visualizer doesn't open.  See below  for the java error messages following pushing the visualizer button.

Hope someone can set me straight.  I like what I see so far.

Thanks,

Bill

C:\Documents and Settings\Bill\My Documents\grbl\UniversalGcodeSender-v1.0.7>java -jar -Xmx256m UniversalGcodeSender.jar
[Boot] INFO:  myJarPath=file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGco
deSender.jar
[JarClassLoader] INFO:  setProperties(com.simontuffs.onejar.JarClassLoader@aa37a6)
[JarClassLoader] INFO:  oneJarPath=file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/U
niversalGcodeSender.jar
[Boot] INFO:  using JarClassLoader: com.simontuffs.onejar.JarClassLoader
[JarClassLoader] INFO:  oneJarPath=file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/U
niversalGcodeSender.jar
[JarClassLoader] INFO:  findResource(): unable to locate "resources/MessagesBundle_en.properties"
Aug 22, 2014 3:28:36 PM com.willwinder.universalgcodesender.SettingsFactory <clinit>
INFO: Settings file location: C:\Documents and Settings\Bill\.UniversalGcodeSender.properties
Aug 22, 2014 3:28:36 PM com.willwinder.universalgcodesender.SettingsFactory loadSettings
INFO: Loading settings.
Stable Library
=========================================
Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7
[JarClassLoader] INFO:  findResource() found: "com/jogamp/common/os/Platform.class" for caller null in codebase lib/gluegen-r
t.jar
Catched FileNotFoundException: JAR entry lib/gluegen-rt-natives-windows-i586.jar!/ not found in C:\Documents and Settings\Bil
l\My Documents\grbl\UniversalGcodeSender-v1.0.7\UniversalGcodeSender.jar, while TempJarCache.bootstrapNativeLib() of jar:file
:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/gluegen-rt
-natives-windows-i586.jar!/ (file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/Univers
alGcodeSender.jar!/lib/ + gluegen-rt-natives-windows-i586.jar)
[JarClassLoader] INFO:  findResource() found: "jogamp/nativewindow/NWJNILibLoader.class" for caller null in codebase lib/jogl
-all.jar
Catched FileNotFoundException: JAR entry lib/jogl-all-natives-windows-i586.jar!/ not found in C:\Documents and Settings\Bill\
My Documents\grbl\UniversalGcodeSender-v1.0.7\UniversalGcodeSender.jar, while addNativeJarLibsImpl(classFromJavaJar class jog
amp.nativewindow.NWJNILibLoader, classJarURL jar:file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeS
ender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all.jar!/jogamp/nativewindow/NWJNILibLoader.class, nativeJarBaseName jogl-all
): jogl-all-natives-windows-i586.jar + file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0
.7/UniversalGcodeSender.jar!/lib/ -> jar:file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalGcodeSender-v1
.0.7/UniversalGcodeSender.jar!/lib/jogl-all-natives-windows-i586.jar!/
[JarClassLoader] INFO:  findResource() found: "jogamp/nativewindow/NWJNILibLoader.class" for caller null in codebase lib/jogl
-all.jar
Catched IOException: TempJarCache: addNativeLibs: jar:file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalG
codeSender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all-natives-windows-i586.jar!/, previous load attempt failed, while addN
ativeJarLibsImpl(classFromJavaJar class jogamp.nativewindow.NWJNILibLoader, classJarURL jar:file:/C:/Documents%20and%20Settin
gs/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all.jar!/jogamp/nativewindow/NWJNI
LibLoader.class, nativeJarBaseName jogl-all): jogl-all-natives-windows-i586.jar + file:/C:/Documents%20and%20Settings/Bill/My
%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/ -> jar:file:/C:/Documents%20and%20Settings/Bill/
My%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all-natives-windows-i586.jar!/
[JarClassLoader] INFO:  findResource() found: "jogamp/nativewindow/NWJNILibLoader.class" for caller null in codebase lib/jogl
-all.jar
Catched IOException: TempJarCache: addNativeLibs: jar:file:/C:/Documents%20and%20Settings/Bill/My%20Documents/grbl/UniversalG
codeSender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all-natives-windows-i586.jar!/, previous load attempt failed, while addN
ativeJarLibsImpl(classFromJavaJar class jogamp.nativewindow.NWJNILibLoader, classJarURL jar:file:/C:/Documents%20and%20Settin
gs/Bill/My%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all.jar!/jogamp/nativewindow/NWJNI
LibLoader.class, nativeJarBaseName jogl-all): jogl-all-natives-windows-i586.jar + file:/C:/Documents%20and%20Settings/Bill/My
%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/ -> jar:file:/C:/Documents%20and%20Settings/Bill/
My%20Documents/grbl/UniversalGcodeSender-v1.0.7/UniversalGcodeSender.jar!/lib/jogl-all-natives-windows-i586.jar!/
Exception in thread "AWT-EventQueue-0" javax.media.opengl.GLException: Unable to set pixel format 5 for device context 0x1a01
0c96: error code 0
        at jogamp.opengl.windows.wgl.WindowsWGLGraphicsConfigurationFactory.updateGraphicsConfiguration(WindowsWGLGraphicsCon
figurationFactory.java:216)
        at jogamp.opengl.windows.wgl.WindowsWGLGraphicsConfiguration.updateGraphicsConfiguration(WindowsWGLGraphicsConfigurat
ion.java:142)
        at jogamp.opengl.windows.wgl.WindowsWGLDrawable.setRealizedImpl(WindowsWGLDrawable.java:68)
        at jogamp.opengl.GLDrawableImpl.setRealized(GLDrawableImpl.java:182)
        at javax.media.opengl.awt.GLCanvas$2.run(GLCanvas.java:602)
        at jogamp.common.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:74)
        at javax.media.opengl.awt.GLCanvas.validateGLDrawable(GLCanvas.java:583)
        at javax.media.opengl.awt.GLCanvas.reshape(GLCanvas.java:662)
        at java.awt.Component.setBounds(Unknown Source)
        at java.awt.BorderLayout.layoutContainer(Unknown Source)
        at java.awt.Container.layout(Unknown Source)
        at java.awt.Container.doLayout(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validate(Unknown Source)
        at java.awt.Container.validateUnconditionally(Unknown Source)
        at java.awt.Window.pack(Unknown Source)
        at com.willwinder.universalgcodesender.visualizer.VisualizerWindow.<init>(VisualizerWindow.java:81)
        at com.willwinder.universalgcodesender.MainWindow.visualizeButtonActionPerformed(MainWindow.java:1256)
        at com.willwinder.universalgcodesender.MainWindow.access$500(MainWindow.java:67)
        at com.willwinder.universalgcodesender.MainWindow$6.actionPerformed(MainWindow.java:270)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" javax.media.opengl.GLException: Unable to create temp OpenGL context for device contex
t 0x1a010c96
        at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:306)
        at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:572)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:485)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:645)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
        at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:996)
        at javax.media.opengl.Threading.invoke(Threading.java:193)
        at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:449)
        at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:499)
        at sun.awt.RepaintArea.paintComponent(Unknown Source)
        at sun.awt.RepaintArea.paint(Unknown Source)
        at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" javax.media.opengl.GLException: Unable to create temp OpenGL context for device contex
t 0x1a010c96
        at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:306)
        at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:572)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:485)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:645)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
        at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:996)
        at javax.media.opengl.Threading.invoke(Threading.java:193)
        at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:449)
        at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:499)
        at sun.awt.RepaintArea.paintComponent(Unknown Source)
        at sun.awt.RepaintArea.paint(Unknown Source)
        at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by pepik-knize** [comment]
I'm having this issue as well on Ubuntu 14.04. Any update?

**Comment by winder** [comment]
I updated the Java OpenGL library recently, could you try the v1.0.8 nightly and see if that resolves the problem?

**Comment by jgeisler0303** [comment]
Works like a charm now, thanks! (Didn't try while running, but assume that there will be no difference)
