### ISSUE TITLE
Error On launch

### ISSUE THREAD

**Issue by magicplug** [winder/Universal-G-Code-Sender#241]
Latest version UGS build  march 21  .. nothing happen obnlythe message below 

C:\Users\PrintServe\Downloads>java -jar -Xmx256m UniversalGcodeSender.jar
[Boot] INFO:  myJarPath=file:/C:/Users/PrintServe/Downloads/UniversalGcodeSender.jar
[JarClassLoader] INFO:  setProperties(com.simontuffs.onejar.JarClassLoader@be858)
[JarClassLoader] INFO:  oneJarPath=file:/C:/Users/PrintServe/Downloads/UniversalGcodeSender.jar
[Boot] INFO:  using JarClassLoader: com.simontuffs.onejar.JarClassLoader
[JarClassLoader] INFO:  oneJarPath=file:/C:/Users/PrintServe/Downloads/UniversalGcodeSender.jar
[JarClassLoader] INFO:  findResource() found: "com/willwinder/universalgcodesender/utils/Version.class" for caller null in codebase main/Universal G-Code Sender.jar
[JarClassLoader] INFO:  findResource(): unable to locate "resources/MessagesBundle_en.properties"
Mar 21, 2015 3:58:01 PM com.willwinder.universalgcodesender.utils.SettingsFactory loadSettings
INFO: Loading settings.
Mar 21, 2015 3:58:01 PM com.willwinder.universalgcodesender.utils.SettingsFactory loadSettings
INFO: Settings file location: C:\Users\PrintServe\UniversalGcodeSender.json
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:315)
        at com.simontuffs.onejar.Boot.main(Boot.java:152)
Caused by: java.lang.NullPointerException
        at com.willwinder.universalgcodesender.MainWindow.initProgram(MainWindow.java:2046)
        at com.willwinder.universalgcodesender.MainWindow.<init>(MainWindow.java:115)
        at com.willwinder.universalgcodesender.MainWindow.main(MainWindow.java:196)
        ... 6 more

----

**Comment by magicplug** [comment]
I fixed the issue just delete UniversalGcodeSender.json and relaunch
