### ISSUE TITLE
Pendant comm_disconnected doubt

### ISSUE THREAD

**Issue by beckmx** [winder/Universal-G-Code-Sender#248]
Hello guys, does anybody know why whenever I get into the Pendant server it always shows "COMM_DISCONNECTED"?

**Comment by OSComputing** [comment]
I get this same response. Using recent UGS Daily V2.0. I can see the IP address in the console.

2015-12-20 15:21:52.785:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
Listening on: http://192.168.55.14:8080
Dec 20, 2015 3:21:53 PM com.willwinder.universalgcodesender.model.GUIBackend addControllerListener
INFO: Adding controller listener.

The pendant doesn't work. I can go to the pendant and see the controls, but at the top there is a message: "COMM_DISCONNECTED." After I click any button the console just endlessly scrolls the following:

Dec 20, 2015 3:24:32 PM com.willwinder.universalgcodesender.model.GUIBackend updateSystemState
INFO: Getting system state 'updateSystemState'
2015-12-20 15:24:32.616:WARN:oejs.AbstractHttpConnection:/getSystemState/
java.lang.NullPointerException
        at com.willwinder.universalgcodesender.model.GUIBackend.updateSystemState(GUIBackend.java:162)
        at com.willwinder.universalgcodesender.pendantui.PendantUI$GetSystemStateHandler.handle(PendantUI.java:211)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Unknown Source)
