### ISSUE TITLE
OSX - nightly build won't start

### ISSUE THREAD

**Issue by maudette01432** [winder/Universal-G-Code-Sender#257]
Michaels-iMac:UniversalGcodeSender maudette01432$ ./start.sh 
[Boot] INFO:  myJarPath=file:/Users/maudette01432/Downloads/UniversalGcodeSender/UniversalGcodeSender.jar
[JarClassLoader] INFO:  setProperties(com.simontuffs.onejar.JarClassLoader@46ae506e)
[JarClassLoader] INFO:  oneJarPath=file:/Users/maudette01432/Downloads/UniversalGcodeSender/UniversalGcodeSender.jar
[Boot] INFO:  using JarClassLoader: com.simontuffs.onejar.JarClassLoader
[JarClassLoader] INFO:  oneJarPath=file:/Users/maudette01432/Downloads/UniversalGcodeSender/UniversalGcodeSender.jar
[JarClassLoader] INFO:  resources/build.properties in main/Universal G-Code Sender.jar is hidden by / (with different bytes)
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/willwinder/universalgcodesender/MainWindow : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:820)
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:727)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:647)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at com.simontuffs.onejar.Boot.run(Boot.java:309)
	at com.simontuffs.onejar.Boot.main(Boot.java:152)

System Info:
Michaels-iMac:UniversalGcodeSender maudette01432$ uname -a
Darwin Michaels-iMac 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

Michaels-iMac:UniversalGcodeSender maudette01432$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

**Comment by maudette01432** [comment]
Installed Java 8 runtime and it starts:

export JAVA_HOME=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
./start.sh
