### ISSUE TITLE
Autoleveler opening a scan containing negative space coordinates fails

### ISSUE THREAD

**Issue by rurigk** [winder/Universal-G-Code-Sender#2571]
### Version

2.1.8

### Hardware / Firmware

GRBL 1.1

### What happened

I tried to open a autoleveler saved scan with "Open scan" button and it shows an error

```
java.lang.IllegalStateException: The supplied file is missing height data for grid point: com.willwinder.universalgcodesender.model.Position@48569148[units=MM,a=NaN,b=NaN,c=NaN,x=19.4,y=-1.6999999999999886,z=NaN]
	at com.willwinder.ugs.platform.surfacescanner.actions.OpenScannedSurfaceAction.lambda$updatePoints$1(OpenScannedSurfaceAction.java:117)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at com.willwinder.ugs.platform.surfacescanner.actions.OpenScannedSurfaceAction.updatePoints(OpenScannedSurfaceAction.java:117)
	at com.willwinder.ugs.platform.surfacescanner.actions.OpenScannedSurfaceAction.actionPerformed(OpenScannedSurfaceAction.java:97)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
[catch] at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

Original settings
![image](https://github.com/user-attachments/assets/d80f2a16-55d9-486f-9853-4b77c8eb32d4)

Settings when i try to import the scan (it resets the minY to 0.0)
![image](https://github.com/user-attachments/assets/9204eab7-29d2-46d5-88e1-efe7fbd1ed09)

I can't redo the scan because the surface is not there anymore because some of traces are already milled (pcb milling)

### How to reproduce

Open this scan file with 2.1.8
[twilight_left_front_scan.txt](https://github.com/user-attachments/files/16325967/twilight_left_front_scan.txt)

Rename to .xyz, github didn't allowed me to upload .xyz files 

### Operating System

Arch Linux

**Comment by rurigk** [comment]
I found out why

In https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-platform/ugs-platform-surfacescanner/src/main/java/com/willwinder/ugs/platform/surfacescanner/Utils.java#L51
uses `Double.MIN_VALUE` but it represents the lowest non-zero positive number

https://stackoverflow.com/questions/3884793/why-is-double-min-value-in-not-negative#3884879

Thats why it goes to 0 on the settings

Changing it to 
```
double maxX = -Double.MAX_VALUE;
double maxY = -Double.MAX_VALUE;
double maxZ = -Double.MAX_VALUE;
``` 
works as expected
