### ISSUE TITLE
Error on OrangePi

### ISSUE THREAD

**Issue by KuleshoffM** [winder/Universal-G-Code-Sender#2611]
### Version

2.1.8

### Hardware / Firmware

GRBL 1.1

### What happened

orangepi@orangepizero2w:/cnc/UniversalGcodeSender$ java -jar -Xmx256m UniversalGcodeSender.jar
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:164)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at com.willwinder.universalgcodesender.MainWindow.<init>(MainWindow.java:110)
        at com.willwinder.universalgcodesender.MainWindow.main(MainWindow.java:218)

### Operating System

Ubuntu

### Anything else

orangepi@orangepizero2w:/cnc/UniversalGcodeSender$ java -version
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

**Comment by breiler** [comment]
What is your desktop environment?

**Comment by KuleshoffM** [comment]
I'm trying to run UGS on OrangePi. I installed Ubuntu there in terminal mode. There is no desktop there.

**Comment by breiler** [comment]
How are you planning to run gcode files?

There is a cli-alternative, look in the ugs-cli.sh

**Comment by KuleshoffM** [comment]
from web...
orangepi:8080

where look ugs-di.sh ?

**Comment by breiler** [comment]
Sorry, it is named "start-cli.sh" and should be available in the UniversalGcodeSender.zip

**Comment by KuleshoffM** [comment]
I was running start-cli.sh . There are no errors, but nothing happens. The web interface is also not available

**Comment by breiler** [comment]
Run `start-cli.sh -h` to print help information.

You will need to run `start-cli.sh -d` to start in a daemon mode which should start the web server.

**Comment by KuleshoffM** [comment]
Its work. Sencs
