### ISSUE TITLE
Visualize Windows does not work on Raspbian / RaspberryPi

### ISSUE THREAD

**Issue by derFrickler** [winder/Universal-G-Code-Sender#47]
Just tried to get the new Visualizer Window running on my RaspberryPi running raspbian 
Found some issues here. 

First, 2 more libs for the arm Platform are needed, which can be found in the Processing project:

gluegen-rt-natives-linux-armv6hf.jar
jogl-all-natives-linux-armv6hf.jar

With this libs added, UniversalGcodeSender compiles and starts. 

Then if i try to open the Visualizer Windows via the Visualize Button i get the following Exception:

Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: javax.media.nativewindow.DefaultGraphicsConfiguration cannot be cast to com.jogamp.nativewindow.awt.AWTGraphicsConfiguration
        at javax.media.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1096)
        at javax.media.opengl.awt.GLCanvas.addNotify(GLCanvas.java:529)
        at java.awt.Container.addNotify(Container.java:2769)
        at javax.swing.JComponent.addNotify(JComponent.java:4734)
        at java.awt.Container.addNotify(Container.java:2769)
        at javax.swing.JComponent.addNotify(JComponent.java:4734)
        at java.awt.Container.addNotify(Container.java:2769)
        at javax.swing.JComponent.addNotify(JComponent.java:4734)
        at javax.swing.JRootPane.addNotify(JRootPane.java:756)
        at java.awt.Container.addNotify(Container.java:2769)
        at java.awt.Window.addNotify(Window.java:770)
        at java.awt.Frame.addNotify(Frame.java:487)
        at java.awt.Window.pack(Window.java:807)
        at com.willwinder.universalgcodesender.VisualizerWindow.<init>(Unknown Source)
        at com.willwinder.universalgcodesender.MainWindow.visualizeButtonActionPerformed(Unknown Source)
        at com.willwinder.universalgcodesender.MainWindow.access$600(Unknown Source)
        at com.willwinder.universalgcodesender.MainWindow$8.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)

Might be a bug with jogl on the arm platform, i will try to find out how to fix this.

**Comment by pelowitz** [comment]
It seems that there has been no forward movement (in four years) on fixing the "Visualize" on the RPi. I'd donate an RPi to someone willing to fix this problem I'd also donate $$$ to the project to see this gets addressed!

**Comment by awd86** [comment]
I'll second that

**Comment by goloplo** [comment]
Any chance to see the visualiser working on RPI in the future?

**Comment by trilitheum** [comment]
Would love to see the visualizer get fixed on the RPi as well!

**Comment by Flugpaul** [comment]
Hello, is there any result for solving the RP - UGS -Plattform "visulize Window" Problem? I just build a CNC Milling mashine (UGS Platform, Raspberry PI, Arduino with GRBL). I can work with UGS on the rasp, but I can't see the milling progress in the window. Only when I connect instead of the RP my windows-Notebook I have the visulize window working.

**Comment by breiler** [comment]
Finally got this working. See these instructions to get it working here: https://github.com/winder/Universal-G-Code-Sender/wiki/Raspberry-Pi
