### ISSUE TITLE
win7 can not run

### ISSUE THREAD

**Issue by yifabin023** [winder/Universal-G-Code-Sender#616]
E:\UniversalGcodeSender2>java -jar -Xmx256m UniversalGcodeSender.jar
四月 08, 2017 1:41:18 上午 com.willwinder.universalgcodesender.utils.SettingsFac
tory loadSettings
信息: Log location: C:\Users\Administrator\.ugs\UniversalGcodeSender.json
四月 08, 2017 1:41:18 上午 com.willwinder.universalgcodesender.utils.SettingsFac
tory loadSettings
信息: Loading settings.
Initializing...
Exception in thread "main" java.util.MissingResourceException: Can't find bundle
 for base name resources.MessagesBundle, locale zh_CN
        at java.util.ResourceBundle.throwMissingResourceException(Unknown Source
)
        at java.util.ResourceBundle.getBundleImpl(Unknown Source)
        at java.util.ResourceBundle.getBundle(Unknown Source)
        at com.willwinder.universalgcodesender.i18n.Localization.initialize(Loca
lization.java:65)
        at com.willwinder.universalgcodesender.i18n.Localization.initialize(Loca
lization.java:54)
        at com.willwinder.universalgcodesender.MainWindow.<init>(MainWindow.java
:124)
        at com.willwinder.universalgcodesender.MainWindow.main(MainWindow.java:2
60)

E:\UniversalGcodeSender2>pause

**Comment by winder** [comment]
This could be a corrupt download. If re-downloading doesn't work try setting the language back to English in the classic GUI before re-launching the platform.
