### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by SenAlex85** [winder/Universal-G-Code-Sender#676]
Hi

Recently I encounter this exception ( mentioned below ) right upon connecting to the COM port
Tried re flushing the Arduino with new GRBL - but seems that nothing helps

as a beginner in CNC I've tried multiple G Code senders
( eventually decided to stay with the Universal G Code Sender )

I am able to run GCode without errors but seems that it is missing steps ( or it takes longer to respond )
but it does not show the machine position neither the work position
Visualization seems to be stuck on it's place 

* The file was exported from EASEL ( I think should be totally suported with Arduino & GRBL )

Please help,
Thanks !

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.willwinder.universalgcodesender.MainWindow.setStatusColorForState(MainWindow.java:2201)
        at com.willwinder.universalgcodesender.MainWindow.statusStringListener(MainWindow.java:2552)
        at com.willwinder.universalgcodesender.AbstractController.dispatchStatusString(AbstractController.java:757)
        at com.willwinder.universalgcodesender.GrblController.handlePositionString(GrblController.java:414)
        at com.willwinder.universalgcodesender.GrblController.rawResponseHandler(GrblController.java:126)
        at com.willwinder.universalgcodesender.AbstractController.rawResponseListener(AbstractController.java:743)
        at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:198)
        at com.willwinder.universalgcodesender.AbstractCommunicator$1.run(AbstractCommunicator.java:165)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

// ------------------------------------------------------------------------------------------------------ //

```
>>> G1X12.971Y21.227F100.0
ok
>>> G1Z3.810F50.0
>>> G0X9.103Y15.322
ok
>>> G1Z-1.000F50.0
ok
>>> G1X8.723Y15.527F100.0
ok
>>> G1X8.637Y15.730F100.0
ok
>>> G1X8.579Y16.377F100.0
ok
>>> G1X8.772Y18.148F100.0
ok
ok
>>> G1X9.037Y18.632F100.0
ok
>>> G1X10.608Y19.745F100.0
ok
>>> G1X11.857Y20.455F100.0
```

**Comment by winder** [comment]
@SenAlex85 this should be all set now, thanks for the report.
