### ISSUE TITLE
v1.0.8 fails to show visualization

### ISSUE THREAD

**Issue by zjor** [winder/Universal-G-Code-Sender#723]
Env: 10.12.5
the following exception is thrown:
`
[JarClassLoader] INFO:  findResource(): unable to locate "natives/macosx-universal/"
[JarClassLoader] INFO:  findResource(): unable to locate "jogamp/nativetag/common/macosx/universal/TAG.class"
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Can't load library: /System/Library/Frameworks/gluegen-rt.Framework/gluegen-rt
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:596)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:96)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:459)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:388)
	at com.jogamp.common.os.Platform$1.run(Platform.java:209)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:179)
	at javax.media.opengl.GLProfile.<clinit>(GLProfile.java:120)
	at javax.media.opengl.awt.GLCanvas.<init>(GLCanvas.java:263)
	at javax.media.opengl.awt.GLCanvas.<init>(GLCanvas.java:230)
	at javax.media.opengl.awt.GLCanvas.<init>(GLCanvas.java:217)
	at com.willwinder.universalgcodesender.visualizer.VisualizerCanvas.<init>(VisualizerCanvas.java:131)
	at com.willwinder.universalgcodesender.visualizer.VisualizerWindow
`

v.1.0.9 shows visualisation correctly on the same environment

**Comment by winder** [comment]
Sorry, but I don't have the time to port bug fixes to older versions of UGS.
